
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
        - name: reddit
          image: imkiran13/reddit:v1 # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your app listens on

